main:
  - name: Suporte
    identifier: suporte
    weight: 100
    url: https://github.com/diogoguilhen/ProductCommunity
    params:
      header: Product Community Suporte
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentações
    parent: suporte
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentations.

  - name: GitHub
    parent: support
    url: https://github.com/diogoguilhen/ProductCommunity
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: support
    url: https://github.com/diogoguilhen/ProductCommunity/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Feature Request
    parent: support
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new or updated features.
  
  - name: Mastodon
    parent: support
    url: https://techhub.social/@hbstack
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
