main:
  - name: Suporte
    identifier: suporte
    weight: 100
    url: https://github.com/diogoguilhen/ProductCommunity
    params:
      header: Product Community Suporte
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentações
    parent: suporte
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: Documentações.

  - name: GitHub
    parent: suporte
    url: https://github.com/diogoguilhen/ProductCommunity
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: Repositorio do código.

  - name: Discussion
    parent: suporte
    url: https://github.com/diogoguilhen/ProductCommunity/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Faça uma pergunta ou compartilhe as suas ideias.

  - name: Bug Report
    parent: suporte
    url: https://github.com/diogoguilhen/ProductCommunity/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Nos conte se encontrou um BUG.

  - name: Feature Request
    parent: suporte
    url: https://github.com/diogoguilhen/ProductCommunity/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Sugestões de novas Features.
  
  - name: X
    parent: suporte
    url: https://twitter.com/ProCommunity_
    weight: 16
    params:
      icon:
        vendor: font-awesome-brands
        name: x-twitter
      description: Nos siga para mais informações e atualizações no Twitter.
