name = "Product Communitys"
license = "MIT"
licenselink = "https://github.com/hbstack/theme/blob/main/LICENSE"
description = "Comunidade dos Product Managers"
homepage = "https://productcommunity.netlify.app"
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Diogo Guilhen"
homepage = "https://diogoguilhen.com.br"
